FROM golang:1.19.5-alpine AS build-env
# Build Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest
ADD ../zeroconf-server /dockerdev
WORKDIR /dockerdev
RUN go build -gcflags="all=-N -l" -o /server
# Final stage
FROM alpine:latest
EXPOSE 40000
WORKDIR /
COPY --from=build-env /go/bin/dlv /
COPY --from=build-env /server /
CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/server"]
